# ----------- CONFIGURABLE START -----------
title:            "Pride Polyphony"
description:      "A space for people to hear LGBTQ solidarity voices around the world"
url:              https://shenchingtou.github.io 
signoff:          "Pride Polyphony" 
facebook_appid:   #none
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Homepage
    url:          /
    external:     false
  - name:         Bookmarks
    url:          /book
    external:     false
  - name:         Travel
    url:          /road
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:title.html
defaults:
  - values:
      layout: "default"
