# ----------- CONFIGURABLE START -----------
title:            "Pride Polyphony"
description:      "A project for the Uhlala Pride Hackathon"
url:              https://liberxue.github.io # 域名
signoff:          "Shenchingtou" # Your name
facebook_appid:   #liberxue
google_analytics: UA-56530919-4
share:            true 
# 分页
paginate: 15
paginate_path: ":num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Submit
    url:          /submit
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /:categories/:title.html
permalink: /:year/:title.html
defaults:
  - values:
      layout: "default"
