# ----------- CONFIGURABLE START -----------
title:            "Pride Polyphony"
description:      "A project for Uhlala Pride Hackathon 2020"
url:              pride-polyphony.netlify.app # 域名
signoff:          "Project" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Book
    url:          /book
    external:     false
  - name:         Random
    url:          /road
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
