# ----------- CONFIGURABLE START -----------
title:            "Blog"
description:      "Blog"
url:              https://shengchingtou.github.io # 域名
signoff:          "LiberXue" # Your name
facebook_appid:   #
google_analytics: #UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     true
  - name:         Book
    url:          /book
    external:     true
  - name:         Random
    url:          /road
    external:     true
  - name:         Archives
    url:          /archives
    external:     true
  - name:         Tags
    url:          /tags
    external:     true
  - name:         About
    url:          /about
    external:     true
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
